'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Microsoft.InteropFormTools.InteropFormProxyGenerator.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error Creating InteropForm Wrapper Classes for Project {0}.
        '''</summary>
        Friend ReadOnly Property ADDIN_STATUS_GENERATED_ERROR_FULL() As String
            Get
                Return ResourceManager.GetString("ADDIN_STATUS_GENERATED_ERROR_FULL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error Creating InteropForm Wrapper Classes.
        '''</summary>
        Friend ReadOnly Property ADDIN_STATUS_GENERATED_ERROR1() As String
            Get
                Return ResourceManager.GetString("ADDIN_STATUS_GENERATED_ERROR1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to   for Project {0}.
        '''</summary>
        Friend ReadOnly Property ADDIN_STATUS_GENERATED_ERROR2() As String
            Get
                Return ResourceManager.GetString("ADDIN_STATUS_GENERATED_ERROR2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to InteropForm Wrapper Classes Generated.
        '''</summary>
        Friend ReadOnly Property ADDIN_STATUS_GENERATED_OK() As String
            Get
                Return ResourceManager.GetString("ADDIN_STATUS_GENERATED_OK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Generating InteropForm Wrapper Classes....
        '''</summary>
        Friend ReadOnly Property ADDIN_STATUS_GENERATING() As String
            Get
                Return ResourceManager.GetString("ADDIN_STATUS_GENERATING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to generate wrapper classes since no InteropForms were found.  Please note that if you are building an Interop UserControl you don&apos;t need to use this Addin, just build the project..
        '''</summary>
        Friend ReadOnly Property ADDIN_STATUS_NONE_GENERATED_OK() As String
            Get
                Return ResourceManager.GetString("ADDIN_STATUS_NONE_GENERATED_OK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to InteropForm Wrapper Class Generator.
        '''</summary>
        Friend ReadOnly Property DISPLAY_CAPTION() As String
            Get
                Return ResourceManager.GetString("DISPLAY_CAPTION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {6BB5F8EE-4483-11D3-8BCF-00C04F8EC28C}.
        '''</summary>
        Friend ReadOnly Property DOCUMENT_TYPE() As String
            Get
                Return ResourceManager.GetString("DOCUMENT_TYPE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This event exposes System.EventArgs as part of its signature..
        '''</summary>
        Friend ReadOnly Property EVENT_ARGS_COMMENT1() As String
            Get
                Return ResourceManager.GetString("EVENT_ARGS_COMMENT1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Any dervied types have been cast down..
        '''</summary>
        Friend ReadOnly Property EVENT_ARGS_COMMENT2() As String
            Get
                Return ResourceManager.GetString("EVENT_ARGS_COMMENT2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Be sure COM client references the Common Language Runtime Library (mscorlib.tlb) or library containing appropriate derived type..
        '''</summary>
        Friend ReadOnly Property EVENT_ARGS_COMMENT3() As String
            Get
                Return ResourceManager.GetString("EVENT_ARGS_COMMENT3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Event {0} will not be generated. Could not find delegate {1}.  Delegate must be explicitly.
        '''</summary>
        Friend ReadOnly Property EventErrMsg() As String
            Get
                Return ResourceManager.GetString("EventErrMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Type {0} is not supported. Event {1} will not be generated..
        '''</summary>
        Friend ReadOnly Property EventErrMsg2() As String
            Get
                Return ResourceManager.GetString("EventErrMsg2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {6BB5F8EF-4483-11D3-8BCF-00C04F8EC28C}.
        '''</summary>
        Friend ReadOnly Property FOLDER_TYPE() As String
            Get
                Return ResourceManager.GetString("FOLDER_TYPE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Type {0} is not supported. Initialize method for constructor with parameter {1}({2}) will not be generated..
        '''</summary>
        Friend ReadOnly Property InitMethodErrMsg() As String
            Get
                Return ResourceManager.GetString("InitMethodErrMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to InteropForm Wrapper Classes.
        '''</summary>
        Friend ReadOnly Property INTEROP_FORM_PROXY_FOLDER_NAME() As String
            Get
                Return ResourceManager.GetString("INTEROP_FORM_PROXY_FOLDER_NAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Global::ctrl+shift+g.
        '''</summary>
        Friend ReadOnly Property KeyBinding() As String
            Get
                Return ResourceManager.GetString("KeyBinding", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error creating Add-In: could not load supported types for generated code.  .
        '''</summary>
        Friend ReadOnly Property LoadSupportedTypesErrMsg() As String
            Get
                Return ResourceManager.GetString("LoadSupportedTypesErrMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Type {0} is not supported. Method {1} will not be generated..
        '''</summary>
        Friend ReadOnly Property MethodErrMsg1() As String
            Get
                Return ResourceManager.GetString("MethodErrMsg1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Type {0} is not supported. Method {1} will not be generated..
        '''</summary>
        Friend ReadOnly Property MethodErrMsg2() As String
            Get
                Return ResourceManager.GetString("MethodErrMsg2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Parameterized properties are not supported. Property {0} will not be generated..
        '''</summary>
        Friend ReadOnly Property ParamPropertyErrMsg() As String
            Get
                Return ResourceManager.GetString("ParamPropertyErrMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Type {0} is not supported. Property {1} will not be generated..
        '''</summary>
        Friend ReadOnly Property PropertyErrMsg() As String
            Get
                Return ResourceManager.GetString("PropertyErrMsg", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
